export enum MessageType {
  JOIN = "JOIN",
  JOINED = "JOINED",
  LEAVE = "LEAVE",
  LEFT = "LEFT",
  USER = "USER",
  USERS = "USERS",
  SESSIONS = "SESSIONS",
  NEWSESSION = "NEWSESSION",
  REMOVESESSION = "REMOVESESSION",
  START = "START",
  STARTED = "STARTED",
  ERROR = "ERROR",
  CARDS = "CARDS",
  ATROW = "ATROW",
  PLAYCARD = "PLAYCARD",
  DRAWCARD = "DRAWCARD",
  WIN = "WIN",
  LOSE = "LOSE",
  END = "END",
  MAU = "MAU",
  KANNNICHT = "KANNNICHT",
  CARD = "CARD",
  AUSSETZEN = "AUSSETZEN",
  PLAYEDCARD = "PLAYEDCARD",
  YOUPLAYEDCARD = "YOUPLAYEDCARD",
}
export enum CardSymbol {
  KREUZ = "KREUZ",
  PIK = "PIK",
  HERZ = "HERZ",
  KARO = "KARO",
}
export enum CardNumber {
  ASS = "A",
  ZWEI = "2",
  DREI = "3",
  VIER = "4",
  FÜNF = "5",
  SECHS = "6",
  SIEBEN = "7",
  ACHT = "8",
  NEUN = "9",
  ZEHEN = "10",
  BUBE = "J",
  DAME = "Q",
  KÖNIG = "K",
}
